name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t podmoskovnykh/cd_docker_project:latest .

      - name: Log in to Docker Hub
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push podmoskovnykh/cd_docker_project:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.SERVER_IP }}'
          username: '${{ secrets.SERVER_USER }}'
          password: '${{ secrets.SSH_PASSWORD }}'
          script: |
            cd /home/ivpodmoskovnykh/cd_docker_project
            docker-compose pull
            docker-compose down
            docker-compose up -d
